"""conversations, speakers and utterances

Revision ID: 160d57fadaa4
Revises: 
Create Date: 2018-06-06 16:24:05.198214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160d57fadaa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_email'), 'speaker', ['email'], unique=True)
    op.create_table('utterance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_id'], ['utterance.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('first_utterance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_utterance_id'], ['utterance.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation')
    op.drop_table('utterance')
    op.drop_index(op.f('ix_speaker_email'), table_name='speaker')
    op.drop_table('speaker')
    # ### end Alembic commands ###
