"""context for conversations

Revision ID: 3749889205ca
Revises: beefbfd31733
Create Date: 2018-07-18 13:36:14.118128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3749889205ca'
down_revision = 'beefbfd31733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('context', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'context')
    # ### end Alembic commands ###
