"""timestamps for conversations

Revision ID: 466799e5d87a
Revises: 53def3e4c2f9
Create Date: 2018-06-11 12:37:15.031771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466799e5d87a'
down_revision = '53def3e4c2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conversation_timestamp'), 'conversation', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_timestamp'), table_name='conversation')
    op.drop_column('conversation', 'timestamp')
    # ### end Alembic commands ###
