"""utterance and conversation tables

Revision ID: e0ddf2686a8e
Revises: 1ef99f1e67c0
Create Date: 2018-06-05 13:59:49.744330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ddf2686a8e'
down_revision = '1ef99f1e67c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utterance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_id'], ['utterance.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_utterance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_utterance_id'], ['utterance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation')
    op.drop_table('utterance')
    # ### end Alembic commands ###
