"""Conversation, Speaker and Utterance tables

Revision ID: e59d5cf6a6ca
Revises: 
Create Date: 2018-06-08 14:39:06.543371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59d5cf6a6ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_email'), 'speaker', ['email'], unique=True)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utterance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=128), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utterance')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_speaker_email'), table_name='speaker')
    op.drop_table('speaker')
    # ### end Alembic commands ###
